#
# Copyright (C) 2020 Argos Notary Coöperatie UA
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: '3.1'

services:
  argos-frontend:
    image: argosnotary/argos-frontend:1.0.2
    environment:
      - BACKEND_URL=http://argos-service:8080
    ports:
      - 80:80
    depends_on:
      - argos-service

  argos-service:
    image: argosnotary/argos-service:1.0.3
    environment:
      spring.config.location: /application.yml
      jwt.token.secret: Z2LcVpgCuGtpb5rBDNIIWGe8RXqYGWDpWFjWhYQUS2Z8rjE2/GTJlu0s6BRYG0Mn0kV8StC9cFE83Jkl68RCkw==
      spring.profiles.active: integration-test
      JAVA_OPTS: '-Xmx1g'
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    volumes:
      - ./compose-application.yml:/application.yml
      
  oauth-stub:
    image: argosnotary/oauth-stub:2.25.1
    environment:
      JAVA_OPTS: '-Xmx500m'
    ports:
      - 8087:8080

  mongodb:
    image: argosnotary/mongo:4.2.8
    ports:
      - 27017:27017
