---
kind: pipeline
type: docker
name: argos-release

platform:
  os: linux
  arch: amd64

steps:
- name: check license
  image: argosnotary/argos-build:3.6.3
  commands:
  - mvn license:check

- name: build and release integrated beta image
  image: plugins/docker
  settings:
    tags:
    - ${DRONE_BRANCH}-beta
    build_args:
    - ARGOS_FRONTEND_VERSION=1.0.0
    - ARGOS_SERVICE_VERSION=1.0.0
    - ARGOS_FRONTEND_IMAGE=argos-frontend
    - ARGOS_SERVICE_IMAGE=argos-service
    context: docker
    dockerfile: docker/Dockerfile
    password:
      from_secret: docker_login_token
    repo: argosnotary/argosnotary
    username:
      from_secret: docker_login_user
  when:
    ref:
      include:
      - "refs/heads/master"
      - "refs/heads/release/*"
    event:
    - push
  depends_on:
  - check license
  
- name: build and release integrated image
  image: plugins/docker
  settings:
    tags:
    - ${DRONE_TAG}
    build_args:
    - ARGOS_FRONTEND_VERSION=1.0.0
    - ARGOS_SERVICE_VERSION=1.0.0
    - ARGOS_FRONTEND_IMAGE=argos-frontend
    - ARGOS_SERVICE_IMAGE=argos-service
    context: docker
    dockerfile: docker/Dockerfile
    password:
      from_secret: docker_login_token
    repo: argosnotary/argosnotary
    username:
      from_secret: docker_login_user
  when:
    event:
    - tag
  depends_on:
  - check license

trigger:
  event:
  - push
  - tag

...
